### ISSUE TITLE
When the code release?

### ISSUE THREAD

**Issue by pribadihcr** [Jianfeng1991/GRCNN-for-OCR#1]
+1

**Comment by Jianfeng1991** [comment]
we will release the code after the conference, thanks for your interest to this work

**Comment by Jianfeng1991** [comment]
@pribadihcr 
we will release the code after the conference, thanks for your interest to this work

**Comment by Jianf-Wang** [comment]
@pribadihcr 
we will release the code and the pre-trained model after the conference.
Thanks for your interest to this work.
