### ISSUE TITLE
请问有tensorflow版本吗？

### ISSUE THREAD

**Issue by 980044579** [Jianfeng1991/GRCNN-for-OCR#2]

**Comment by Jianf-Wang** [comment]
I am not familiar with the tensorflow and we cannot release the TF code now.
Maybe in the future we will try to adapt this work to the tensorflow

**Comment by 980044579** [comment]
Thank you and congratulations for your paper received in nips2017.Good job！

**Comment by Jianfeng1991** [comment]
Are you BUPT's student ?
